global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/einstein_metrics.yml"
  - "rules/resource_metrics.yml"
  - "rules/health_metrics.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'edge-functions'
    static_configs:
      - targets: ['edge-functions:9000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'health-check'
    metrics_path: '/health/metrics'
    static_configs:
      - targets: ['edge-functions:9000']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093'] 