name: Supabase CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Add global permissions (least privilege)
permissions:
  contents: read
  packages: read

env:
  SUPABASE_URL: ${{ vars.SUPABASE_URL }}
  SUPABASE_PROJECT_REF: ${{ vars.SUPABASE_PROJECT_REF }}
  DEPLOY_HOST: ${{ vars.DEPLOY_HOST }}

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    permissions: {}  # No special permissions needed
    defaults:
      run:
        working-directory: ./frontend
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
        env:
          NODE_OPTIONS: '--max-old-space-size=4096'
  
  test-edge-functions:
    runs-on: ubuntu-latest
    permissions: {}  # No special permissions needed
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      
      - name: Run Edge Function tests
        run: deno test --allow-net supabase/functions/calculate/calculate.test.js
  
  lint:
    runs-on: ubuntu-latest
    permissions: {}  # No special permissions needed
    defaults:
      run:
        working-directory: ./frontend
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linting
        run: npm run lint
  
  build-and-push-docker:
    needs: [test-frontend, test-edge-functions, lint]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Needed for pushing to GHCR
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/einstein-field-equations:latest
            ghcr.io/${{ github.repository_owner }}/einstein-field-equations:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: true  # Enable SLSA provenance
          sbom: true  # Generate SBOM
  
  deploy-supabase:
    needs: [test-frontend, test-edge-functions, lint]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions: {}  # No special permissions needed
    environment: prod  # Using 'prod' instead of 'production' to match GitHub's schema
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Supabase CLI
        run: npm install -g supabase
      
      - name: Login to Supabase CLI
        run: supabase login --token "${{ secrets.SUPABASE_ACCESS_TOKEN }}"
      
      - name: Deploy Edge Functions
        run: supabase functions deploy calculate --project-ref "${{ vars.SUPABASE_PROJECT_REF }}"
      
      - name: Deploy Health Check Function
        run: supabase functions deploy health --project-ref "${{ vars.SUPABASE_PROJECT_REF }}"
      
      - name: Deploy Database Migrations
        run: |
          cd supabase
          supabase db push --project-ref "${{ vars.SUPABASE_PROJECT_REF }}"
  
  deploy-to-cloud:
    needs: [build-and-push-docker, deploy-supabase]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions: {}  # No special permissions needed
    environment: prod  # Using 'prod' instead of 'production' to match GitHub's schema
    
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          install -m 600 <(echo "${{ secrets.SSH_PRIVATE_KEY }}") ~/.ssh/id_rsa
          install -m 600 <(echo "${{ secrets.SSH_KNOWN_HOSTS }}") ~/.ssh/known_hosts
      
      - name: Deploy to Digital Ocean
        env:
          DEPLOY_USERNAME: ${{ vars.DEPLOY_USERNAME }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          REPO_OWNER: ${{ github.repository_owner }}
        run: |
          ssh "$DEPLOY_USERNAME@$DEPLOY_HOST" << 'ENDSSH'
            # Pull the latest image
            docker pull ghcr.io/$REPO_OWNER/einstein-field-equations:latest
            
            # Stop the existing container
            docker stop einstein-app || true
            docker rm einstein-app || true
            
            # Run the new container with security options
            docker run -d \
              --name einstein-app \
              --security-opt=no-new-privileges:true \
              --cap-drop=ALL \
              --cap-add=NET_BIND_SERVICE \
              -p 80:80 \
              -e REACT_APP_SUPABASE_URL="$SUPABASE_URL" \
              -e REACT_APP_SUPABASE_ANON_KEY="$SUPABASE_ANON_KEY" \
              --restart unless-stopped \
              ghcr.io/$REPO_OWNER/einstein-field-equations:latest
            
            # Clean up old images
            docker image prune -af
          ENDSSH 